name: Bug report
description: Create a report to help us improve
labels:
  - needs triage
body:
  - type: textarea
    attributes:
      label: What happens?
      description: A short, clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: To reproduce
      description: |
        Please provide steps to reproduce the behavior, preferably a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example). Please adhere to the following guidelines:

        * Format the code, ontology and output as [code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) using triple backticks:

          ````
          ```ttl
          YOUR ONTOLOGY
          ```
          ````
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Environment:"
  - type: input
    attributes:
      label: "OS:"
      placeholder: e.g., Ubuntu
      description: Please include operating system version.
    validations:
      required: true
  - type: input
    attributes:
      label: "ontodoc version:"
      placeholder: e.g., 0.0.2
    validations:
      required: true
