name: Build doc
on:
  release:
    types: [created]

jobs:
  build_doc:
    strategy:
      fail-fast: false
      matrix:
        # python-version: ["3.9", "3.13"]
        python-version: ["3.13"]
        poetry-version: ["2.1.1"]
        # os: [ubuntu-22.04, macos-latest, windows-latest]
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install packages
        run: poetry install
      - name: View poetry --help
        run: poetry run python ontodoc --help
